name = "bytebasev2-com"
compatibility_date = "2024-06-05"
pages_build_output_dir = "./dist"

vars = { ENVIRONMENT = "dev" }

[env.preview]
# vars = { ENVIRONMENT = "preview" }

[env.production]
# vars = { ENVIRONMENT = "production" }
# routes = [
#   "example.com/foo/*",
#   "example.com/bar/*"
# ]
