name = "bytebasev2-com"
compatibility_date = "2024-06-05"
pages_build_output_dir = "./dist"

route = "project-bytebasev2.mlvappstudios.org/*"
vars = { ENVIRONMENT = "dev" }

[env.staging]
# vars = { ENVIRONMENT = "staging" }

[env.production]
# vars = { ENVIRONMENT = "production" }
# routes = [
#   "example.com/foo/*",
#   "example.com/bar/*"
# ]
